### ISSUE TITLE
Not able to build on Ubuntu 22.04

### ISSUE THREAD

**Issue by hydroid7** [LinuxCNC/buster-live-build#26]
Hi,
when try to build the system on Ubuntu 22.04, the following error is thrown:
```
Reading package lists...
E: The repository 'http://deb.debian.org/debian-security buster-security Release' does not have a Release file.
```
This error prevents building the official image. Is there any workaround for this bug?
Thanks!

**Comment by andypugh** [comment]
The problem seems to be that the security patches have moved from deb.debian.org/debian-security/dists/buster to deb.debian.org/debian-security/dists/buster/updates. 
I don't see an easy way to handle that in the auto/config file of this repository, so as a workaround I have deleted the line. 
Not ideal, but I have added the required modification to the linuxcnc.list instead. 
Can you try again?

**Comment by hydroid7** [comment]
Sure, I've tried it. Unfortunately now it uses the default one. A workaround is to disable the repo entirely with `--secure false`. 

With that flag, it downloads some packages, but the installer is not able to find the packages `linux-image-rt-generic` and `linuxcnc-doc-de`.
I'm in doubt that `generic` is the correct package. Maybe `linux-image-rt-amd64` would be the right one?
 
Here is the error output of the command `lb build`:

```
(Reading database ... 9288 files and directories currently installed.)
Removing dctrl-tools (2.24-3) ...
(Reading database ... 9248 files and directories currently installed.)
Purging configuration files for dctrl-tools (2.24-3) ...
Reading package lists...
Building dependency tree...
Reading state information...
[2022-12-25 15:35:43] lb_chroot_install-packages install
P: Begin installing packages (install pass)...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package linux-image-rt-generic
E: Unable to locate package linuxcnc-doc-de
P: Begin unmounting filesystems...
P: Saving caches...
Reading package lists...
Building dependency tree...
Reading state information...
```

**Comment by andypugh** [comment]
Yes, linux-image-rt-amd64 does, at least, work. 

The problem basically is that Buster is now "old stable" and a lot of the debian files have been moved about.
Switching to Bullseye would be good, except that there are no LinuxCNC Bullseye repositories.

**Comment by hydroid7** [comment]
Update: I've set the arch to amd64, like this:
```
	--architecture amd64 \
	--linux-flavours amd64 \
```
Now, was looking for the right `linux-image-rt-amd64` ✅ , but the `linuxcnc-doc-de` ❌  package was still missing. 
I removed it from the `linuxcnc.list` file.

I'ts WIP :)

**Comment by andypugh** [comment]
Why are you doing this? You can download a pre-built ISO (from when it actually worked...) and then just update what needs updating.

**Comment by rodw-au** [comment]
Recommend this issue be closed.
1. Debian Bookworm branch exists now
2. We should not be supporting other distros
3.  Ubuntu have hidden the PREEMPT_RT behind a paywall

**Comment by hydroid7** [comment]
Sure, I'm ok with it. I switched to archlinux which has support for `preempt_rt` out of the box. A big help were for me the pages
- https://forum.linuxcnc.org/9-installing-linuxcnc/43928-linuxcnc-2-9-on-arch-linux
- https://www.forum.linuxcnc.org/9-installing-linuxcnc/42143-linuxcnc-on-arch
