### ISSUE TITLE
error during build

### ISSUE THREAD

**Issue by probotix** [LinuxCNC/buster-live-build#34]
find: ‘binary’: No such file or directory
E: An unexpected failure occurred, exiting...

**Comment by andypugh** [comment]
Can you elaborate on this slightly? For a start which branch are you using, and what are you trying to do?

**Comment by probotix** [comment]
I figured it out. The instructions didn't make it clear that I needed to change to the buildbot repositiories manually. It makes it sound like live-build makes the change for you.

We use bookworm and build a pre-seeded unattended install with a customized mate Desktop that makes it look much like the old 2.6 Ubuntu 10.04 version. I'd love to contribute to this but I and not sure how to use git to submit my contributions.

**Comment by andypugh** [comment]
The suggestions at https://linuxcnc.org/docs/stable/html/code/contributing-to-linuxcnc.html apply equally well to the linuxcnc live-build repository (and "wlo" - the main linuxcnc web page). 
I suspect that you have already cloned linucnc-live-build so if you want to make changes it is just a case of pushing those changes from your own clone to github and then making a pull-request on github.
