### ISSUE TITLE
Frimware not loading for RTL8168

### ISSUE THREAD

**Issue by ghost** [LinuxCNC/buster-live-build#35]
Board involved Asrock J3355B, is a known working board with no issues. 

During network setup installer not loading firmware and unable to setup network.
During the live session network performs as expected.
Have tried both the on board NIC and a NIC via PCIe interface, with same behaviors. 

Used 12.5 netinst image from debian, no issue with network setup. (raspi-firmware issue was not there)
Then did manual installation of RT kernel & linuxcnc-uspace.
Once installed no issue with NIC, but did install the recommended dkms.

**Comment by andypugh** [comment]
Does this require the firmware to be added to our package list, or does this feel like a problem in the underling installer?

**Comment by ghost** [comment]
It's in the package list, I checked under the firmware folder, but it does feel like a problem in the installer.

**Comment by ghost** [comment]
OK...after some further investigation.

It would appear to be whilst the installer is trying to configure the network during DHCPv6 stage.

I've seen this happen on a number of machines & VirtualBox instances.

The workaround I've used is below

When booting press TAB on the installer entry.
This will give you the "kernel command line"
Press the space bar then type ipv6.disable=1, then proceed to boot.

ATM I have only tested this using VirtualBox on a Linux Mint host.

I also tested a Debian 12.5 bookworm live image, I wanted to see if it was a 12.4 or 12.5 installer issue, and I got the same failure during the DHCPv6 stage. I don't think it's an issue with Linuxcnc, I saw a few posts with OpenMediaVault users having issues during the network stage.

**Comment by ghost** [comment]
Further investigation.....

When using VirtualBox to run an install, having the Network set to NAT works without disabling ipv6, at my site having the adapter bridged stalls without disabling ipv6. ATM I can not get my pfSense to hand  out ipv6 addresses, ISP doesn't do IPv6 for wireless internet, this may be causing that issue.
Playing around with building ISO with ipv6.disable=1 and will report back. (also trying to get bottom panel to properly display launchers)

**Comment by andypugh** [comment]
I merged your PR, does that mean that this can be closed?

**Comment by ghost** [comment]
Yeah, the issue was the IPV6 thing not the firmware.

**Comment by ghost** [comment]
All sweet now
