### ISSUE TITLE
Build dying when it reaches non-free firmware

### ISSUE THREAD

**Issue by probotix** [LinuxCNC/buster-live-build#36]
Build dying when it reaches non-free firmware. Just started recently. Seems to work now with this config option:

--parent-archive-areas "main contrib non-free non-free-firmware"

**Comment by andypugh** [comment]
Is it possible to submit this as a pull request?

**Comment by probotix** [comment]
Well, I have a highly customized version with a complete pre-seeder and custom splash screen and other stuff. Can I submit a pull request for just this one issue?

**Comment by andypugh** [comment]
Sorry, I have been otherwise engaged. 

Does the LinuxCNC version (without your mods) fail? If not then it probably doesn't count as a bug with this repository?

**Comment by andypugh** [comment]
Actually looking, we seem to already have what you suggest: 
https://github.com/search?q=repo%3ALinuxCNC%2Flinuxcnc-live-build%20non-free&type=code
The change appeared to go in 9 months ago. 
https://github.com/LinuxCNC/linuxcnc-live-build/blame/50ba019bf536a9cb14e9f8f7e66b2a4f23f67f20/auto/config#L11

**Comment by andypugh** [comment]
Closing this, please re-open if I have missed something.
